# Generated by Django 5.2.4 on 2025-09-26 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteNE',
            fields=[
                ('cod_ne', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ug', models.BigIntegerField()),
                ('pi', models.CharField(max_length=200)),
                ('nd', models.BigIntegerField()),
                ('data', models.DateField()),
                ('a_liquidar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liquidado_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note NE',
                'verbose_name_plural': 'Notes NE',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cod_ne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ne_control.notene')),
            ],
        ),
        migrations.CreateModel(
            name='ActionTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('previ_date', models.DateField()),
                ('description', models.TextField()),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cod_ne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_taken', to='ne_control.notene')),
            ],
        ),
    ]
