# Generated by Django 5.2.4 on 2025-10-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='pi',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
