# Generated by Django 5.2.4 on 2025-07-15 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NoteNE',
            fields=[
                ('cod_ne', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ug', models.IntegerField()),
                ('pi', models.FloatField()),
                ('nd', models.IntegerField()),
                ('dias', models.IntegerField()),
                ('a_liquidar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liquidado_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_contato', models.DateField()),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ne_control.responsible')),
            ],
        ),
    ]
