# Generated by Django 5.2.4 on 2025-07-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_control', '0002_responsible_notene'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notene',
            options={'verbose_name': 'Note NE', 'verbose_name_plural': 'Notes NE'},
        ),
        migrations.AlterField(
            model_name='notene',
            name='data_contato',
            field=models.CharField(max_length=10),
        ),
    ]
