# Generated by Django 5.2.4 on 2025-07-19 18:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ne_control', '0003_action_taken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='action_taken',
            new_name='ActionTaken',
        ),
    ]
