# Generated by Django 5.2.4 on 2025-07-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_control', '0003_alter_notene_options_alter_notene_data_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notene',
            name='ug',
            field=models.BigIntegerField(),
        ),
    ]
