# Generated by Django 5.2.4 on 2025-07-19 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_control', '0004_rename_action_taken_actiontaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontaken',
            name='cod_ne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_taken', to='ne_control.notene'),
        ),
    ]
