# Generated by Django 5.2.4 on 2025-07-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_control', '0004_alter_notene_ug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notene',
            name='pi',
            field=models.CharField(max_length=200),
        ),
    ]
