# Generated by Django 5.2.4 on 2025-07-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_control', '0005_alter_notene_pi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notene',
            name='nd',
            field=models.BigIntegerField(),
        ),
    ]
