# Generated by Django 5.2.4 on 2025-08-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ne_control', '0007_rename_user_id_claim_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notene',
            old_name='data_contato',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='notene',
            name='dias',
        ),
    ]
