# Generated by Django 5.2.4 on 2025-08-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_control', '0008_rename_data_contato_notene_data_remove_notene_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notene',
            name='data',
            field=models.DateField(),
        ),
    ]
