# Generated by Django 5.2.4 on 2025-09-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_workplace_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='workplace_id',
        ),
    ]
