# Generated by Django 5.2.4 on 2025-09-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_workplace_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='workplace_id',
            new_name='workplace',
        ),
    ]
