# Generated by Django 5.2.4 on 2025-08-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_status_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('responsible', 'Responsável por NE')], max_length=20),
        ),
    ]
