# Generated by Django 5.2.4 on 2025-09-26 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_workplace_id_user_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.workplace'),
        ),
    ]
